### ISSUE TITLE
Help Page: GIFs are too small

### ISSUE THREAD

**Issue by amadr** [hochschule-darmstadt/MetaAutoML#485]
- The GIFs are too small, making it difficult for the user to recognize what is happening on them.
- High resolution GIFs are very big, that's why we can use MP4 videos 

### Tasks
- [x] Capture new help videos instead of GIFs
- [x] Autoplay the video and the video should be in loop
- [x] The size of the videos should be small (<1mb)
- [x] The videos can be expanded to full-screen
