### ISSUE TITLE
UX improvements for Model: Details page

### ISSUE THREAD

**Issue by amadr** [hochschule-darmstadt/MetaAutoML#501]
1. The user would like to be able to read through the details better. It would be good if there was a button that enlarged the text field.
2. A search function would make it much easier to find things. 
3. User wants a text field like he is used to for log files (e.g. Notepad).
4. A log file should start at the bottom so that you can scroll up (as you are used to).

### Tasks
- [x] Implement a button that opens the details in a large popup window.
- [x] Implement a searchbar to find words in the log.
- [x] The text field should be horizontally and vertically scrollable and should not make text breaks automatically. 
- [ ] Display the last output at the bottom first and make the field scrollable upwards (like the log of other applications).

**Comment by amadr** [comment]
Old AutoML output details:
<img width="500" alt="image" src="https://github.com/hochschule-darmstadt/MetaAutoML/assets/69305541/f6938151-f4e5-4719-a0d8-ccc8f44b97c9">

New AutoML Output Details with a popup:
<p float="left" align="middle">
  <img src="https://github.com/hochschule-darmstadt/MetaAutoML/assets/69305541/4086ce5e-6a95-442d-ba7f-7ae7c0c02dda" width="400" />
  <img src="https://github.com/hochschule-darmstadt/MetaAutoML/assets/69305541/6b7e596c-ae7d-4f87-a480-7d53f0a8277d" width="400" /> 
</p>
The small output is vertically and horizontally scrollable. The output in the popup is horizontally scrollable. The popup can be closed by clicking anywhere outside the popup or by scrolling to the bottom and clicking the "Close" button.
