### ISSUE TITLE
Improvement of Train Configution Page

### ISSUE THREAD

**Issue by Anne19marie** [hochschule-darmstadt/MetaAutoML#544]
**Tasks**

- [ ] The training is not finished at this point. 
- [ ] The selection options of the target are not sorted.
- [ ] Not several target can be selected anyway 

**Solutions**

- [ ] Change it to "Start training"
- [ ] Sort the selection options of the target in alphabetical order.
- [ ] Only one target should be selectable.
