### ISSUE TITLE
Dataset Analysis

### ISSUE THREAD

**Issue by tpachmann** [hochschule-darmstadt/MetaAutoML#73]
Calculate various metrics regarding the input dataset, which are added to the blackboard to be used by the controller later (e.g. to show hints / perform automated optimizations):

- Data types & encoding (which may need feature engineering), data ranges (if applicable)
- Dataset size (amount of data points)
- Outliers / extreme values
- Features with (many) missing values
- Redundant features (duplicate columns)
- Redundant samples (duplicate rows)
- Feature correlation
(- Imputing missing values)

These metrics may be used for automatic or recommended data cleaning/feature engineering operations.

**Tasks:**
- [ ] Define JSON schema for result
- [ ] Implement data analysis manager (which is invoked when uploading a new dataset)
- [ ] Add UI for the dataset analysis
